const skills={
    1:[
        {
            title:"HTML",
            level:6,
        },
        {
            title:"CSS",
            level:5,
        },
        {
            title:"Bootstrap",
            level:6,
        },
        {
            title:"Javascript",
            level:3,
        },
        {
            title:"Typescript",
            level:1,
        },
        {
            title:"Tailwind CSS",
            level:2,
        },
        {
            title:"React JS",
            level:4,
        },
        {
            title:"Figma",
            level:1,
        },
    ],
    2:[
        {
            title:"PostgreSQL",
            level:1,
        },
        {
            title:"Node.js",
            level:4,
        },
        {
            title:"MongoDB",
            level:4,
        },
        {
            title:"GIT",
            level:2,
        },
        {
            title:"PHP",
            level:1,
        },
        {
            title:"SQL",
            level:4,
        },
        {
            title:"Express.js",
            level:4,
        },
    ],
};
export default skills;